pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *pg
  port: 5432
  database: spade
  host: localhost
  username: developer
  password: developer

production:
  <<: *pg
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>