# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2648c437ccaf36fc5fc74ab2bbd0e510690173c8849d7f6fed63e8becba28c75d156eaf7f910ba819b5cd0c281223bb76c241174faee7bff0fe2b29518603a

test:
  secret_key_base: a1d36326c09ea101648e889b49907774ebb258d71dfcf8695b2d53b8aead98ff31e415e5cc0ccf7319950ca1a6dbd0f83fc3dd2f7b5b2b49d2a0aa381667687f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
